services:
  savestrm:
    build: .
    container_name: savestrm
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
    volumes:
      - ./data:/app/data
      - /mnt/media:/media
    restart: unless-stopped
